language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - 2.3.1
  # - jruby-18mode # JRuby in 1.8 mode
  # - jruby-19mode # JRuby in 1.9 mode
  # - rbx-18mode
  # - rbx-19mode
matrix:
  allow_failures:
  - rvm: 1.9.3
  - rvm: 2.0.0
  - rvm: 2.1.0
